apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: us.icr.io/liberty_test/petclinic:latest
        imagePullPolicy: Always    
        name: petclinic        
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m



